language: node_js
node_js:
- '5'
- '6'
branches:
  only:
  - master
  - develop
notifications:
  email:
  - nfantone@gmail.com
cache:
  bundler: true
  directories:
  - node_modules
script: npm run validate && ./node_modules/.bin/codecov
before_script:
- npm install codecov
deploy:
  provider: npm
  email: nfantone@gmail.com
  api_key:
    secure: cmFVW4aGW7TLiywEBWZc36GEwk/K+G+SrbLT8qd9aMYX1M964hoLn0htVrWpm9XCqMr46G5AaMzkOThOzOKjbt2Gj14vWOnj4r/W5Ckhm/WRBGmMz8gpabm7imS/Vr23EelPYZfBfAzowz8n+BlmH03EvTxM8hXxNRzNUECXahN/KDWMkvJSpj/6hjT9L66a/lXFatFPeNC2+By2ILl/cLJVpAGoR7nt61KvehDKxNJh605pfTka2HbeG1WWgJ+9kMTjH6OoTZ4/BktShkvjpJsYwyePVpbGKIm/URozZ6s98cHHdjJT272PnIsISY6Lt6b1LbRE3lOKWJUmxpZEIVRLknX5qMuX+t+IGhBjf3dOIMAFxdJPVzzE96ARe3dQZH+7IflHI+9uCW89ky3ne9dZzApQMkKe/dHlkHpIGft1qR6IYHTBTnUp0Wd1jZzVgABsRI/lY95kO9rpOCPJszEEYpZtXOEm03Hh69OR/1KeRZ9rzEbLB7aiL+sRGYMoEqlQlBW0uUQ4TWQvx9pSVSIXQnPdhf/WIVNO9/FTJ+bIAlbrtIbjN5PSCyUhojPayE5F6P/sqhlKqlEmNPNhFS03FOMfymNu5GHRQZTpLtFlHCk+xTaQnJn1QP74VG4kzOCQOGx1Mr9AmhrmtSrS97GBvKoLZ7T24CURh6Fv9IY=
  on:
    tags: true
    repo: nfantone/mu-koan-server
